server:
  port: 8081
  servlet:
    context-path: /luckymoney

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://agileloop.mysql.polardb.rds.aliyuncs.com/testdb
    username: testdb
    password: testdb@18036
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true